# Colors
set -g @color-blue_slate "#64a1c2"
set -g @color-blue_dark "#466480"
set -g @color-graphite "#181818"
set -g @color-white "#d8d8d8"

# Status Bar
set -g status on
set -g status-interval 5
set -g status-style "fg=#{@color-white}"

set -g status-left "#[fg=#{@color-graphite},bg=#{@color-blue_dark}]#[fg=#{@color-white}] #S #[fg=#{@color-blue_dark},bg=#{@color-graphite}]"
set -g status-right "#[fg=#{@color-graphite},bg=#{@color-blue_dark}]#[fg=#{@color-graphite},bg=#{@color-blue_dark}]#[fg=#{@color-white}] %b %d, %H:%M "

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@color-graphite},bg=#{@color-white}]#[fg=#{@color-white},bg=#{@color-white}]#[fg=#{@color-graphite},bg=#{@color-white}]#I #W #[fg=#{@color-white},bg=#{@color-graphite}]"
setw -g window-status-current-format "#[fg=#{@color-graphite},bg=#{@color-blue_slate}]#[fg=#{@color-blue_slate},bg=#{@color-blue_slate}]#[fg=#{@color-white},bg=#{@color-blue_slate}]#I #W #[fg=#{@color-blue_slate},bg=#{@color-graphite}]"

# Message Bar
set -g message-style "fg=#{@color-white},bg=#{@color-blue_dark},fill=#{@color-blue_dark},width=100%"
set -g message-command-style "bg=#{@color-graphite},fill=#{@color-graphite},fg=#{@color-blue_slate},width=100%"

# Panes
set -g pane-border-style "fg=#{@color-white}"
set -g pane-active-border-style "fg=#{@color-blue_slate}"
