# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General
set -g mouse on
set -g set-titles on
set -g base-index 1
set -g display-time 1000
set -g history-limit 10000
set -s escape-time 0
setw -g mode-keys vi
setw -g pane-base-index 1

# Sessions
bind S command-prompt -p "New Session Name:" "new-session -A -s '%%'"

# Panes & Windows
unbind x
bind x kill-pane
unbind &
bind & kill-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind c new-window -c "#{pane_current_path}"

set -g pane-border-style "fg=#d8d8d8"
set -g pane-active-border-style "fg=#466480"

# Status Bar
set -g status-position bottom
set -g status-interval 5
set -g status-left "[ #S ] "
set -g status-right "[ %b %d, %H:%M ]"
set -g status-style "bg=#466480,fg=#d8d8d8"

# Message Bar
set -g message-style "bg=#64a1c2,fill=#64a1c2,fg=#d8d8d8,width=100%"
set -g message-command-style "bg=#64a1c2,fill=#64a1c2,fg=#d8d8d8,width=100%"

# Copy Mode
bind v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
set-hook -g after-copy-mode "set -p cursor-style block"

# Miscellaneous
bind r source-file ~/.config/tmux/tmux.conf \; display-message " ✓ "
