# Subtitles
sub-scale=1
sub-font="Calibri"
sub-font-size=32
sub-blur=0
sub-bold=no
sub-italic=no
sub-outline-color="#000000"
sub-back-color="#000000"
sub-outline-size=1
sub-border-style=outline-and-shadow
sub-color="#FFFFFF"

# Windows
keep-open=yes
title-bar=no

# OSD
osc=no
